site_name: PHP Architecture Tester
site_description: Easy to use architecture testing tool for PHP
site_url: https://example.com/foo/
repo_url: https://github.com/carlosas/phpat/

docs_dir: ./docs
exclude_docs: .assets

theme:
  name: material
  features:
    - toc.integrate
    - footer
  palette:
    primary: deep-orange
    accent: deep-orange

nav:
  - Introduction: 'index.md'
  - Getting started: 'getting-started.md'
  - Examples: 'examples.md'
  - Documentation: [
    Rules: 'documentation/rules.md',
    Selectors: 'documentation/selectors.md',
    Assertions: 'documentation/assertions.md',
    Configuration: 'documentation/configuration.md',
    Other features: 'documentation/other.md'
  ]
  - Contributing: 'contributing.md'
  - About: 'about.md'
