#!/usr/bin/env php
<?php

declare(strict_types=1);

use PhpAT\DependencyInjection\Provider;
use Symfony\Component\DependencyInjection\ContainerBuilder;

$autoload = is_file(__DIR__.'/../../autoload.php')
    ? __DIR__.'/../../autoload.php'
    : __DIR__.'/vendor/autoload.php';

require $autoload;

if (PHP_VERSION_ID < 70100) {
    \fwrite(\STDERR, 'Required at least PHP version 7.1.0 but your version is '.PHP_VERSION.PHP_EOL);
    exit(1);
}

$container = new ContainerBuilder();
$provider  = new Provider($container, $autoload, $argv);
$container = $provider->register();

try {
    $app = $container->get('app');
    $app->execute();
} catch (\Exception $e) {
    exit(1);
}
