#!/usr/bin/env php
<?php

declare(strict_types=1);

use PhpAT\App\Provider;
use PhpAT\Input\ArgvInput;
use Symfony\Component\DependencyInjection\ContainerBuilder;

$autoload = is_file(__DIR__.'/../../autoload.php')
    ? __DIR__.'/../../autoload.php'
    : __DIR__.'/vendor/autoload.php';

require $autoload;

if (PHP_VERSION_ID < 70200) {
    \fwrite(\STDERR, 'Required at least PHP version 7.2.0 but your version is '.PHP_VERSION.PHP_EOL);
    exit(1);
}

error_reporting(E_ALL);
ini_set('display_errors', 'stderr'); // send php warnings to stderr
gc_disable(); // performance boost

$input = new ArgvInput();

$container = new ContainerBuilder();
$provider  = new Provider($container, $autoload, $input);
$container = $provider->register();

try {
    $app = $container->get('app');
    $app->execute();
} catch (\Exception $e) {
    echo $e->getMessage();
    exit(1);
}
